- name: Download Private key
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
    dest: "{{ ansible_env.HOME }}/.ssh/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0400

- name: Download Public key
  get_url:
    url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
    dest: "{{ ansible_env.HOME }}/.ssh/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0400

- name: Create OSP keypair
  os_keypair:
    cloud: ospcloud
    state: present
    name: ansible_ssh
    public_key_file:  "{{ ansible_env.HOME }}/.ssh/openstack.pub"
    # public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
